### ISSUE TITLE
not work for me!

### ISSUE THREAD

**Issue by jalaltb** [peymanebrahimi/MaterialJalaliMomentAdapter#2]
This not work for me!
I use angular 11. Just translate month and other to farsi. but date (31-days) can not work!

**Comment by peymanebrahimi** [comment]
Would you please provide me more information about your issue?
A sample code would be very useful.

**Comment by zahra-delafkar** [comment]
this is not work correctly for me

**Comment by peymanebrahimi** [comment]
What is the error?
